version: '3'

services:
  bootstrap1:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - IS_BOOTSTRAP=true
    ports:
      - "5000:5000"
    networks:
      - blockchain_network
    tty: true
    stdin_open: true


  node11:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - IS_BOOTSTRAP=false
    ports:
      - "5001:5000"
    networks:
      - blockchain_network
    tty: true
    stdin_open: true


  node22:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - IS_BOOTSTRAP=false
    ports:
      - "5002:5000"
    networks:
      - blockchain_network
    tty: true
    stdin_open: true


  node33:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - IS_BOOTSTRAP=false
    ports:
      - "5003:5000"
    networks:
      - blockchain_network
    tty: true
    stdin_open: true


  node44:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - IS_BOOTSTRAP=false
    ports:
      - "5004:5000"
    networks:
      - blockchain_network
    tty: true
    stdin_open: true


networks:
  blockchain_network:
    driver: bridge
